### ISSUE TITLE
Should frp.event.dom be in it's own module?

### ISSUE THREAD

**Issue by mikkoh** [robin-allen/frp.js#2]
I really like how low level and minimal `frp` is vs something like `bacon`.

However I wonder if a function like `frp.event.dom` is very similar to bacon's methodology where you throw all the bells in whistles into one monolithic library.

A thought would be to make another module which contains the function `frp.event.dom`.

I'd like to hear your thoughts on this as I could see there being a lot of useful functions/modules for creating streams/events in the future.

As an example I created a module which returns a function which returns an `Event` which will fire based on a `requestAnimationFrame` loop.

https://github.com/jam3/frp-tick

**Comment by mikkoh** [comment]
Obviously another solution would be to do something like `require( 'frp/event/dom' )` but I wonder if "own modules" is more scalable for the future.

**Comment by rogual** [comment]
This is a good idea. I'll probably take out `dom` soon.

**Comment by mikkoh** [comment]
@robin-allen So you think separate modules are the way to go vs containing in `rfp` and using pathing?

**Comment by rogual** [comment]
I'm leaning that way, yes.
