### ISSUE TITLE
Smarter signals/cells?

### ISSUE THREAD

**Issue by colllin** [robin-allen/frp.js#4]
This is a cool package.  It's the most approachable FRP library I've found.  Are you still using it, or have you moved onto another package?

I would like to see signals and cells be a little "smarter", and only fire changes if the value actually changed.  Meaning that if the value of `thing` is `2`, then calling `thing.set(1), thing.set(1)` would only fire one change to its listeners.  Not a debounce, but change detection.  The first `thing.set(1)` would cause listeners to re-run, the second call to `thing.set(1)` would be ignored, because it doesn't change the value.

**Comment by colllin** [comment]
I expected it to behave this way initially.  Then I found an infinite loop in my application where the /logout page called `userTokenStore.set(null)`, which updated the app authorization and re-rendered the components (the /logout page), which in turn called `userTokenStore.set(null)` again...

**Comment by rogual** [comment]
Hey, I'm glad you found it useful!

I do use it myself, quite heavily; I just haven't needed to update it in a while.

You can get the behaviour you want using `unique`, which I've just realized I haven't documented. Use it like so:

```
myCell = Cell();
mySignal = myCell.signal.unique();

myCell.set(1);
myCell.set(1);
// mySignal only registers one change
```

The notion of “equality” in JS can be a little slippery. You can pass a comparator to `unique` to specify what you mean by “the same” — if you don't, you get a comparison based on `===`.

**Comment by colllin** [comment]
Exactly what I needed. Thank you.

**Comment by rogual** [comment]
Updated the README to mention it.
